<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- Plataforma -->
		<TargetFramework>net8.0-android</TargetFramework>
		<MauiVersion>8.0.100</MauiVersion>

		<!-- MAUI -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>

		<!-- Proyecto -->
		<OutputType>Exe</OutputType>
		<RootNamespace>Handheld</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- App -->
		<ApplicationTitle>ServiciosYa</ApplicationTitle>
		<ApplicationId>com.serviciosya.handheld</ApplicationId>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- Android -->
		<SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
	</PropertyGroup>


	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.png" Color="#FFFFFF" BaseSize="1280,720" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>


	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\xml\network_security_config.Designer.xml" />
	</ItemGroup>


	<ItemGroup>
	  <Compile Remove="Models\ItemInquiryDto.cs" />
	  <Compile Remove="Services\ItemService.cs" />
	  <Compile Remove="Services\MovementsService.cs" />
	  <Compile Remove="Services\PickService.cs" />
	  <Compile Remove="Services\ReceivingLineService.cs" />
	  <Compile Remove="Services\ReceivingService.cs" />
	  <Compile Remove="Services\ShipmentLineService.cs" />
	  <Compile Remove="Services\ShipmentService.cs" />
	  <Compile Remove="ViewModels\InventoryMovementsViewModel.cs" />
	  <Compile Remove="ViewModels\ItemInquiryViewModel.cs" />
	  <Compile Remove="ViewModels\PickHeadersViewModel.cs" />
	  <Compile Remove="ViewModels\ReceivingHeadersViewModel.cs" />
	  <Compile Remove="ViewModels\ReceivingLineViewModel .cs" />
	  <Compile Remove="ViewModels\ShipmentLineViewModel.cs" />
	</ItemGroup>


	<ItemGroup>
	  <None Remove="Platforms\Android\Resources\xml\network_security_config.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Helpers\" />
	  <Folder Include="Constants\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Components\Cards\Card.xaml.cs">
	    <DependentUpon>Card.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Languages\AppResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Views\MyRequestsPage.xaml.cs">
	    <DependentUpon>MyRequestsPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Languages\AppResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Components\Bars\Bar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Components\Cards\Card.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\AboutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ChangePasswordPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\RegisterPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="ViewModels\MainModel.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HomePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MyRequestDetails.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MyRequestsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ServicePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ServiceRequestPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
